
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Timer;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.tinyos.packet.*;
import net.tinyos.message.*;

public class Frame1 extends javax.swing.JFrame {

    PortListener serialPortGateWay;
    PrintWriter out;
    netAccepter net;

    public Frame1() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WSN");
        setMinimumSize(new java.awt.Dimension(450, 510));
        setPreferredSize(new java.awt.Dimension(520, 550));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(500, 200));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Node", "Temprature"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(500, 150));
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 220));
        jScrollPane1.setRequestFocusEnabled(false);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setToolTipText("");
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 37));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 60));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel13.setText("Port");
        jLabel13.setToolTipText("");
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 14));
        jPanel3.add(jLabel13);

        jTextField2.setText("/dev/ttyUSB1");
        jTextField2.setToolTipText("");
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel3.add(jTextField2);

        jButton3.setText("Open");
        jButton3.setToolTipText("");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        serialPortGateWay.Close();
    }//GEN-LAST:event_formWindowClosed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //open port function
      
        
      /*  if (jButton3.getText().equals("Open")) {
            // serialPortGateWay = new PortListener(this, new String[]{"-comm", "serial@com" + jTextField2.getText() + ":iris"}); //create a port listener object
            serialPortGateWay = new PortListener(this, new String[]{"-comm", "serial@" + jTextField2.getText() + ":telosb"}); //create a port listener object
            serialPortGateWay.start(); //start listening to port
            jButton3.setText("Close");
        } else {
            serialPortGateWay.Close();
            jButton3.setText("Open");
        }*/
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    void display(String s) {
        jTextArea2.append(s + "\n");
        jTextArea2.setCaretPosition(jTextArea2.getDocument().getLength() - 1);
    }

    synchronized void processMessage(Packet pkt) {
        if (pkt.type == Packet.HELLO) {
            double degree = (-40) + pkt.data / 100.0;
            String s = String.format("%.2f", degree);
            jTable1.setValueAt(s, pkt.sender, 1);
            jTable1.setValueAt(pkt.sender + "", pkt.sender, 0);
            if(net!=null)
                net.send(pkt.sender+":"+pkt.data);
        }

    }

}
